### ISSUE TITLE
Static assets does not served in dev mode

### ISSUE THREAD

**Issue by predaytor** [yusukebe/hono-and-remix-on-vite#1]
thanks for setting this stuff up, everything is working great in production! But in developer mode, there seems to be a problem with the serving of static assets.

For Node.js we can use `import { serveStatic } from '@hono/node-server/serve-static'`, but in our case we use `import { staticAssets } from 'remix-hono/cloudflare'` which relies on the internal Cloudflare `env.ASSETS` variable for production mode.

Only `/favicon.ico` works, but trying to access any other resource from the `/public` folder results in an error:

`http://localhost:5173/assets/logo.svg`
```bash
No routes matched location "/assets/logo.svg" 
```
---
Plus, it can't handle css side-effect imports:

`/app/styles.css`:
```css
* {
    box-sizing: border-box;
}
```
`/app/root.tsx`:
```tsx
import './styles.css'

// ...

export default function App() {
  return <Outlet />
}
```
works as intended while using css url import:
```tsx
import styles from './styles.css?url'

export const links: LinksFunction = () => [
  { rel: 'stylesheet', href: styles },
]

// ...

export default function App() {
  return <Outlet />
}
```
```bash
> vite


  VITE v5.2.10  ready in 917 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
10:29:03 PM [vite] Pre-transform error: Cannot read properties of undefined (reading 'get')
10:29:03 PM [vite] Error when evaluating SSR module /app/root.tsx: failed to import "/app/styles.css"
|- TypeError: Cannot read properties of undefined (reading 'get')
    at TransformContext.transform (file:///Users/predaytor/projects/hono-and-remix-on-vite/node_modules/.pnpm/vite@5.2.10_@types+node@20.12.7/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:31665:56)
    at Object.transform (file:///Users/predaytor/projects/hono-and-remix-on-vite/node_modules/.pnpm/vite@5.2.10_@types+node@20.12.7/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:51133:62)
    at async loadAndTransform (file:///Users/predaytor/projects/hono-and-remix-on-vite/node_modules/.pnpm/vite@5.2.10_@types+node@20.12.7/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:53888:29)
    at async instantiateModule (file:///Users/predaytor/projects/hono-and-remix-on-vite/node_modules/.pnpm/vite@5.2.10_@types+node@20.12.7/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:54932:10)

10:29:03 PM [vite] Error when evaluating SSR module virtual:remix/server-build: failed to import "/app/root.tsx"
|- TypeError: Cannot read properties of undefined (reading 'get')
    at TransformContext.transform (file:///Users/predaytor/projects/hono-and-remix-on-vite/node_modules/.pnpm/vite@5.2.10_@types+node@20.12.7/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:31665:56)
    at Object.transform (file:///Users/predaytor/projects/hono-and-remix-on-vite/node_modules/.pnpm/vite@5.2.10_@types+node@20.12.7/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:51133:62)
    at async loadAndTransform (file:///Users/predaytor/projects/hono-and-remix-on-vite/node_modules/.pnpm/vite@5.2.10_@types+node@20.12.7/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:53888:29)
    at async instantiateModule (file:///Users/predaytor/projects/hono-and-remix-on-vite/node_modules/.pnpm/vite@5.2.10_@types+node@20.12.7/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:54932:10)

TypeError: Cannot read properties of undefined (reading 'get')
    at TransformContext.transform (file:///Users/predaytor/projects/hono-and-remix-on-vite/node_modules/.pnpm/vite@5.2.10_@types+node@20.12.7/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:31665:56)
    at Object.transform (file:///Users/predaytor/projects/hono-and-remix-on-vite/node_modules/.pnpm/vite@5.2.10_@types+node@20.12.7/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:51133:62)
    at async loadAndTransform (file:///Users/predaytor/projects/hono-and-remix-on-vite/node_modules/.pnpm/vite@5.2.10_@types+node@20.12.7/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:53888:29)
    at async instantiateModule (file:///Users/predaytor/projects/hono-and-remix-on-vite/node_modules/.pnpm/vite@5.2.10_@types+node@20.12.7/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:54932:10) {
  plugin: 'vite:css-post',
  id: '/Users/predaytor/projects/hono-and-remix-on-vite/app/styles.css',
  pluginCode: '* {\n    box-sizing: border-box;\n}'
}
```

**Comment by yusukebe** [comment]
Hi @predaytor ! Thank you for using it.

About the first problem, I don't know if it's the best way, but you can import the files such as in `/assets/*` by setting up `vite.config.ts` properly.

https://github.com/yusukebe/hono-and-remix-on-vite/pull/3

Second problem. It was not good, so I fixed it to support CSS side-effects imports.

https://github.com/yusukebe/hono-and-remix-on-vite/pull/2

**Comment by predaytor** [comment]
@yusukebe, working great! but yes, we need to find a way to serve any static resource (like nested in folders or at the top level) from `/public`. Thx very much for this!

**Comment by tobimori** [comment]
Any clues on how to solve this?
